# fly.toml app configuration file generated for studyhall on 2025-12-28T22:28:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'studyhall'
primary_region = 'iad'

[build]

[env]
  FLASK_ENV = 'production'
  DATA_DIR = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[mounts]]
  source = "studyhall_data"
  destination = "/app/data"
